### ISSUE TITLE
Add mention of single-quote character literals.

### ISSUE THREAD

**Issue by jemc** [ponylang/pony-tutorial#102]
As far as I can tell, single-quote character literals are not documented in the tutorial anywhere.  This would have prevented some confusion reported in https://github.com/ponylang/ponyc/issues/756.

**Comment by SeanTAllen** [comment]
Any  thoughts on where in the current tutorial structure to put this @jemc?

**Comment by jmiven** [comment]
I was wondering if Pony had character literals when I found this issue, so my beginner-level input might be helpful.

I would expect to find such information in the Expressions chapter, near the Variables section. I also looked in the "Primitives" section (chapter 2) though, because I remembered that it mentioned integers.

**Comment by SeanTAllen** [comment]
@jemc is this still not documented?

**Comment by SeanTAllen** [comment]
Does #250 address this?

**Comment by jemc** [comment]
I don't think #250 addresses it, because it didn't add anything related to character literals like `'A'`.

**Comment by mfelsche** [comment]
With https://github.com/ponylang/pony-tutorial/pull/223 being merged these are documented.
