### ISSUE TITLE
Clarify that case functions are not method overloading

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/pony-tutorial#106]
This conversation from IRC a reasonable question to ask based on the content currently in the tutorial:

<img width="1086" alt="screenshot 2016-04-20 21 27 26" src="https://cloud.githubusercontent.com/assets/193596/14695290/b79a16ec-073e-11e6-95cc-d45cd4b1b95e.png">

**Comment by Nyarum** [comment]
@SeanTAllen I missed you message in IRC chat. Thank you for that ticket and an explanations.

**Comment by aturley** [comment]
Those places that say "Pony doesn't support overloaded methods/functions" should provide more guidance. While the statement is true, it doesn't actually help because case functions will give most people the behavior they expect in the specific cases mentioned in the documentation (infix operators and methods with different argument types, assuming we aren't also talking about methods with different numbers of arguments).

What's the specific thing (or things) that we want people to understand about case functions that makes them different from "overload functions"? I can think of a few things:
* implemented as `match` statements (really more of an implementation detail)
* they can have guards
* they cannot be overload with respect to argument count
* they can do argument matching
Are there other important things that should be called out when explaining to people why they should think of them as "overloaded functions"?

**Comment by aturley** [comment]
@SeanTAllen any thoughts on this? I talked to @sylvanc today and he thought the big things were:
* the current implementation doesn't do an exhaustive match, so case function return types are always a union that includes None
* case functions don't provide a way to "overload" on argument count

**Comment by jemc** [comment]
The only other point I can think of is that, as with `match` statements, the order of declaration can be significant - where cases overlap, the earlier-declared case "wins".

**Comment by SeanTAllen** [comment]
@aturley you seem to have a pretty good handle on this one, when you have a bit of time, can you update this bit of documentation?

**Comment by aturley** [comment]
Sure.
