### ISSUE TITLE
Using FFI: An example showing call-back handling with OpenGL

### ISSUE THREAD

**Issue by jkleiser** [ponylang/pony-tutorial#11]
It would be very interesting if you could include an example showing call-back handling with OpenGL.

**Comment by doublec** [comment]
Do you have an OpenGL API in mind that uses callbacks to use for the example?

**Comment by aturley** [comment]
I think that in general there should be a discussion somewhere in there that covers callbacks, since there are some subtle points that should be addressed.

I spent a little bit of time working with the sqlite library, and one of the things that took me a little while to figure out (with @sylvanc's help) was how the callback function would be called. It also took me a few tries to get the arguments right. It should probably also mention that a shim function may be required if the function's parameters are not in the "correct" order (with the receiver as the first parameter).

Maybe this should be moved to a different issue about generally discussing callback functions (or even more generally, calling Pony code from C) rather than discussing it as part of this issue.

@jkleiser would a general discussion of callbacks be useful, or are there specific OpenGL issues that you're having?

**Comment by SeanTAllen** [comment]
@jkleiser there's a callbacks section to the tutorial now. I think that is good. If you'd be interested in how to do OpenGL, I'd ask on the user mailing list and perhaps someone can show that specifically or you could get someone to do a blog post.
