### ISSUE TITLE
Adding special 'aliasing' rules for immutable machine/value/primitive builtin types

### ISSUE THREAD

**Issue by MrMormon** [ponylang/pony-tutorial#118]
Namely that booleans, numbers, and such are copied so that `is` will be different from `==`. [Here](https://github.com/ponylang/pony-tutorial/blob/master/capabilities/aliasing.md) could be a good place to add this, but I don't know where to mention the no-mutable-rcap rule yet.

Along with this I'm thinking of adding an example of how to 'box' these types so they can be used like any other object, with the caveat that benchmarking or profiling should guide this decision.

**Comment by SeanTAllen** [comment]
I created an issue for the is/==/match issue that trips people up. The rest of this is outside the scope of a tutorial. Feel free to write up your thoughts in a blog post.

**Comment by jemc** [comment]
Based on our discussion on the mailing list, you seem to be confusing a lot of concepts together, and to be hung up on the idea of the machine words being a special case in the type system or the language.  Again, as I said on the mailing list, from the perspective of the type system and the language, there are *no* "special 'aliasing' rules" for machine word types.  They are some differences that come into play when it comes to FFI, but documenting them as special cases anywhere else in the tutorial would be misleading and distracting from the real concepts that govern Pony code.

> immutable machine/value/primitive builtin types

Please don't use the word "primitive" when you're talking about machine word types.  At best, it's confusing to people that read it, and at worst, you're confusing yourself as well.

> Namely that booleans, numbers, and such are copied so that `is` will be different from `==`.

The `is` operator is different from the `==` operator for all objects.  The `is` operator compares identity, while the `==` operator invokes the `eq` method on the first object to do a comparison with the second object (intended for comparing structural equality, but it can use any strategy that the object implements).  Again, the machine word types are *not* a special case here.

> I don't know where to mention the no-mutable-rcap rule yet.

Again, as I explained on the mailing list, the machine word types are *not* a special case when it comes to not allowing any mutable ref caps to be created.  I can easily create my own `class` that only has a `new val` constructor (and no other constructors), so that the only instances that can be created will be created as `val`, and a `val` can never be aliased or `recover`ed as something mutable.  Or I can create my own `primitive`, and it will work the same way except for the fact that only one instance will ever exist, so all calls to the constructor will return the same static, stateless instance.  These are the rules that govern Pony code, and they apply to all types just the same.

> adding an example of how to 'box' these types

Here's another place where your choice of words is confusing.  "Boxing" is a process that happens when machine words are part of a type union, so that their type can be identified at runtime to distinguish from the other types in the union.

> so they can be used like any other object

As I've tried to explain on the mailing list, they already *can* be used like any other (immutable) object.

**Comment by jemc** [comment]
As one more note, aliasing any object, including machine word types, will retain the identity compared by `is`, so I'm not sure what you're driving at with this having some difference of semantics for machine word types - it doesn't.

**Comment by MrMormon** [comment]
I'll address these criticisms in order. The mailing list discussion didn't answer several of my concerns.

> Please don't use the word "primitive" when you're talking about machine word types.

http://www.ponylang.org/ponyc/builtin--index/ and https://github.com/ponylang/pony-tutorial/blob/master/types/primitives.md#built-in-primitive-types do. Should I use 'value types'? Does the built-in-primitives-types section need to be changed? 

> The is operator is different from the == operator for all objects.

> machine word types are not a special case when it comes to not allowing any mutable ref caps to be created

Either this is a distinction in practice (AlmostAnythingElse might need to be 'ref'):
```
let a = U8(0)
let b: U8 = a
a == b // true
a is b // false <----------------

let c = AlmostAnythingElse()
let d = c
c == d // true if eq() implementation compares structure only
c is d // true, right? <-----------------
```
or there needs to be a justification for the standard library's _implementation_ making a distinction in practice of disallowing ref rcaps on primitive types.

> "Boxing" is a process that happens when machine words are part of a type union, so that their type can be identified at runtime

That's one way to box. Another way is putting a value type behind a pointer (anonymous objects?) for any other reason.

> aliasing any object, including machine word types, will retain the identity compared by is

The [page on aliasing](https://github.com/ponylang/pony-tutorial/blob/master/capabilities/aliasing.md#what-counts-as-making-an-alias) I wanted to PR against also uses the term 'alias' for passing arguments to methods, but because machine types _have_ to be immutable how would there not be copying from a machine type to a function it's passed to such that an `is` comparison between the two would be false?

**Comment by SeanTAllen** [comment]
```
let a = U8(0)
let b: U8 = a
a == b // true
a is b // false <----------------
```

incorrect.

a is b.

try it.

```
actor Main
  new create(env: Env) =>
    let a = U8(0)
    let b: U8 = a
    if a is b then
      env.out.print("a is b")
    else
      env.out.print("a is not b")
    end
```

**Comment by jemc** [comment]
As @SeanTAllen points out (and as I have been trying to point out throughout this discussion.  Your understanding of `is` with regard to machine word types is wrong, and your snippet is wrong.  As I've said, "aliasing any object, including machine word types, will retain the identity compared by `is`".

> Does the built-in-primitive-types section need to be changed? 

The section says "The `primitive` keyword is also used to introduce certain built-in "machine word" types. Other than having a value associated with them, these work like user-defined primitives."  Your use of the term "primitive" as a *synonym* for machine word types is confusing, because machine word types *are* implemented as primitives, but primitives *are not* just machine word types - they also include all user-defined types. 

The machine word types are implemented as `primitive`s, but they are not the only primitives, so just calling them "primitives" is misleading.  

> That's one way to box. Another way is putting a value type behind a pointer (anonymous objects?) for any other reason. I could be completely wrong about what boxing means in computer science, but this isn't relevant.

You're right that "what boxing means in computer science" is not relevant.  I'm talking about what "boxing" means for the implementation of machine word types *in Pony*.  When you use this term to mean something different, you are using confusing language, as I originally said.  We want to discourage confusing language, *especially* in the tutorial, where we are trying to teach the important concepts in Pony with as much clarity as possible.

**Comment by MrMormon** [comment]
I was completely wrong about same-function aliasing, and I'm glad. Thank you for responding so quickly. Boxing has a meaning that Pony would be better off not obfuscating in its tutorial. It could be a very specific type of boxing, or it could be boxing in a specific circumstance. Anywho,

What is a user-defined primitive that doesn't use the `primitive` keyword, as opposed to a user-defined something else? I don't understand how you two use the word.

And my last questions again:

> because machine types have to be immutable how would there not be copying from a machine type to a function it's passed to such that an `is` comparison between the two would be false?

Am I wrong in the same way as for same-function aliasing? I have no idea how to test this (boxing/`is`ing machine words in fields?).

> or there needs to be a justification for the standard library's implementation making a distinction in practice of disallowing ref rcaps on [machine word] types // corrected

Which means that I'm very interested in the justification, which I also think belongs in the tutorial or _somewhere_ because it's a standard library implementation distinction even if it's not a linguistic one.

Sorry for making the last day frustrating. I want to know, not experiment. Rcaps are an exception of course because complete documentation isn't the end of learning to use them.

**Comment by SeanTAllen** [comment]
Don't post code that you haven't run and make assumptions on what happens. That is a good way to burn a lot of good will. I'm not particularly inclined to answer questions when you didn't but in the basic legwork of running your example code. I hope you can understand that. I spent a lot of my time answering questions that if you had run code based on what you thought happened, I wouldn't have had to. That disrespectful to our time.

**Comment by MrMormon** [comment]
I don't have access to Pony at this time. I'm doing a lot of Linux distro-hopping, and I have to find something that works with my backup computer.

**Comment by jemc** [comment]
> What is a user-defined primitive that doesn't use the `primitive` keyword, as opposed to a user-defined something else? I don't understand how you two use the word.

When I use the word "primitive", I'm talking about types that use the keyword `primitive`.

> Am I wrong in the same way as for same-function aliasing? I have no idea how to test this (boxing/ising machine words in fields?).

Yes, you're wrong in the same way.

> or there needs to be a justification for the standard library's implementation making a distinction in practice of disallowing ref rcaps on [machine word] types // corrected

Once again, machine word types are *not a special case here*.  The fact that you can't have mutable machine word in Pony is a consequence of the type system that also applies to all other objects.  Please read again my explanation above (and in the mailing list) regarding types that only have `new val` constructors.

Regarding *why* this choice was made (to implement machine words as immutable types), well, it's because a mutable machine word doesn't make coherent sense.  What does it mean to "mutate" the number `2`?  There's no sane definition of what this would mean.  What you *really* want is to *replace* it with another number, not *mutate* it.  This is how you work with immutable objects - you have one immutable object and you replace it with another that has the difference that you want.  Once again, this is not a special case for machine words.  For a good example of non-trivial immutable types, check out "persistent data structures".  We have a few in Pony in the `collections/persistent` package.

**Comment by MrMormon** [comment]
Okay, thanks, dropping. So ref capabilities would only be useful if there were e.g. an in-place add()?

**Comment by jemc** [comment]
Once again, it doesn't make sense to *mutate* a number.  A number doesn't have any state, other than its identity.  In Pony, the identity of an object can never change.

**Comment by MrMormon** [comment]
There is nothing novel about treating numbers like objects instead of the immutables Pony likes.

**Comment by jemc** [comment]
I don't know what else to tell you other than what I've already said.  If you don't want to believe me, then you don't have to.  `¯\_(ツ)_/¯`
