### ISSUE TITLE
Grammar error in "Consume and Destructive Read"

### ISSUE THREAD

**Issue by snej** [ponylang/pony-tutorial#128]
First sentence:

> And important part of Pony's capabilities are being able to say "I'm done with this thing". 

Should be '**An** important part of Pony's capabilities **is** being able to say "I'm done with this thing"'.

**Comment by jemc** [comment]
Thanks for the correction.

For simple changes like this, it's probably easiest to make a little pull request using [the GitHub "edit" interface](https://github.com/ponylang/pony-tutorial/edit/master/capabilities/consume-and-destructive-read.md).  If you did that, it would surely get merged quickly.

Otherwise, someone will probably get to this within a few days when they get a chance.  Again, you're not obligated to make a pull request when you suggest a change, but it's the fastest way to get things done, especially for small changes.  Even if I make this correction, it would be through me making a pull request using the same process, not committing directly.
