### ISSUE TITLE
Section about quiescence as it relates to program termination.

### ISSUE THREAD

**Issue by jemc** [ponylang/pony-tutorial#157]
We need a section about quiescence as it relates to program termination.

This is definitely a frequently asked question, and I don't think there's anything in the tutorial about it.  It definitely confused me a bit when I was first learning Pony, and having it explained in the tutorial would have helped immensely.

**Comment by SeanTAllen** [comment]
Agreed. I've answered this question 3 times in less than a week and more than that in the last month.

**Comment by rhagenson** [comment]
Luckily, you also answered this question for me three years after this issue opened, @SeanTAllen. 

Trying to determine where this is best put in the tutorial. We do not have a section on quiescence, program termination, or otherwise to "attach" this to so I am thinking either this can either go in Types->Actors or Gotchas->Termination (new subsection). Either way adding that the program terminates when all actors are GCed and individual actors are GCed when:

- there are no aliases to them (cant be sent new messages by other actors)
- not registered for events from the runtime (via epoll, kqueue etc)
- have an empty message queue

Thoughts on location of this information and any additional points on quiescence to add?

**Comment by EpicEric** [comment]
@rhagenson See #408. It suggests adding a new chapter.

**Comment by rhagenson** [comment]
Thank you for directing me to the issue, Eric. Will begin work on the new chapter to knock down both issues. Will also skim the other issues to find possible inclusions to this new chapter.
