### ISSUE TITLE
The "error" in factorial function in Methods chapter is not described

### ISSUE THREAD

**Issue by ei-grad** [ponylang/pony-tutorial#183]
It would be nice to have a reference to error handling docs after the factorial function example. Without it the "if x < 0 then error end" line looks like error :-).

**Comment by ei-grad** [comment]
https://github.com/ponylang/pony-tutorial/blob/master/expressions/methods.md#functions

**Comment by aturley** [comment]
It seems like there are a few different questions we should keep in mind here:

1. This example exists to illustrate tail recursion. Is this in a appropriate place to introduce that concept, or could it be move to follow the error section of the tutorial?
2. Would the reference still be necessary if the factorial example came "after" a discussion of `error`? I've put "after" in quotation marks, because we may not be able to safely assume that someone is reading the tutorial linearly.
3. Is the factorial function the appropriate example to illustrate tail recursion? It has the advantage of being one that many people are familiar with, but could another one be used here?
4. Could the example be simplified to return 0 if the value is negative, with a note about how one could handle it differently? I'd actually argue that this would be an idiomatic Pony solution, since other undefined functions such as division by 0 return 0 rather than raise an exception.

OK, now I've talked myself into changing the example to return 0 instead of raising an error. Any other thoughts?
