### ISSUE TITLE
Are the compile and run sections in the 'Hello World' page correct?

### ISSUE THREAD

**Issue by kevinmcfarlane** [ponylang/pony-tutorial#187]
See [Hello World](https://tutorial.ponylang.org/getting-started/hello-world.html).

When I ran this in Docker for Windows, instead of

Writing **./helloworld.o**
Linking **./helloworld**

I got

Writing **./main.o**
Linking **./main**

And to run it 

docker run -v Some_Absolute_Path/helloworld:/src/main ponylang/ponyc **./main** (same as ponyc readme)

So should 

$ **./helloworld**

be

$ **./main**

If I am right then presumably this isn't?

> Does the name of the directory matter? Yes, it does. It's the name of your program! When your program is compiled, the resulting executable binary will have the same name as the directory your program lives in.

**Comment by SeanTAllen** [comment]
Outside of the context of docker, they are correct. I'm not sure if they are correct for Docker. @jemc?

**Comment by jemc** [comment]
The docs are indeed correct, though it takes some docker-thinking to understand why.

> Does the name of the directory matter? Yes, it does. It's the name of your program! When your program is compiled, the resulting executable binary will have the same name as the directory your program lives in.

In the case of docker, you are mounting your code as a volume with `-v Some_Absolute_Path/helloworld:/src/main`.  This means that the `Some_Absolute_Path/helloworld` directory on your host is being mounted as `/src/main` inside the container (which happens to be the default working directory of the docker container).  Because the compiler is running inside the container, it sees the directory name as being `main`, and has no way of seeing the host's name for the directory (in this case, `helloworld`).

This should be pretty intuitive to those who have used docker before, which I was expecting to be the main audience for the ponyc docker container.  Hopefully the additional instructions you recently added to the README will help bridge the gap.

**Comment by kevinmcfarlane** [comment]
Thanks Joe. As it happens I'm new to both Docker and Pony! Wanting to play with Pony was my motivation for looking into Docker, as it seemed a convenient way to go. :)

Maybe we could just add an extra sentence such as I've done here?

(If you're using Docker, you'd write something like $ docker run -v Some_Absolute_Path/helloworld:/src/main ponylang/ponyc, depending of course on what the absolute path to your helloworld directory is. **If you're using Docker for Windows please see [here](https://github.com/ponylang/ponyc/blob/master/README.md)**. )

**Comment by jemc** [comment]
I'd prefer not to clutter this section of the tutorial with specifics about Docker. How about something like this?

> This tutorial assumes you're using a native binary of the Pony compiler. If you're using the Docker container, please see [this section of the README] for instructions about compiling and executing programs.

**Comment by kevinmcfarlane** [comment]
I only suggested it because the tutorial is already referencing Docker in the parentheses, i.e., the bit before my bold sentence. But I'm fine either way.

**Comment by SeanTAllen** [comment]
Looks like this was addressed at some point. Closing.
