### ISSUE TITLE
Give some scenarios and language comparison of capabilities

### ISSUE THREAD

**Issue by 17studio** [ponylang/pony-tutorial#192]
It is hard to understand Chapter 4: Capabilities quickly. I read this chapter for several times and I think it is hard to express a complex concept by some description. In my opinion, a good way to express a concept  to engineers is to give the scenario.

The following URL gives a language comparison of what is capability in rust. It helps me to find a way to grasp the meaning of capabilities.
https://www.reddit.com/r/rust/comments/34rszb/pony_type_and_memory_safe_language/

I try to express the meaning of capabilities in C++ roughly:

-     isolated --> unique_ptr<T>
-     value --> const value definition
-     reference --> private fields of an actor
-     box --> make passed argument const, whether the origin is mutable/immutable
-     transition --> not initialized value, if initialized, change to immutable
-     tag --> actor ref

I think some sample codes will help to understand the concepts. I read the source code of the standard library of PONY and it really help me. box & trn is a little hard to understand, but with the sample code, I get across it.

**Comment by SeanTAllen** [comment]
I think it is hard to understand quickly because its a non-obvious concept.

I would not that the url you referenced contains numerous small mistakes. I don't think trying to express what different capabilities are based on a specific language is very helpful. Its only helpful if you know the given language. I prefer the language agnostic descriptions currently given.

I'm closing this, however, if someone wants to try a PR that improves the descriptions of reference capabilities in a language agnostic way, perhaps with examples, we'd happily accept that.
