### ISSUE TITLE
Add "Receiver" to the lexicon

### ISSUE THREAD

**Issue by non-Jedi** [ponylang/pony-tutorial#198]
Several times in reading the tutorial, I found the need to remind myself of what is meant by a pony "receiver" and checked the lexicon. Ended up flipping through old sections to figure it out from context.

**Comment by SeanTAllen** [comment]
@non-Jedi are you up for opening a PR for this?

**Comment by non-Jedi** [comment]
@SeanTAllen I can take a stab; I didn't because I'm worried that as a newcomer to the language, I wouldn't be very precise in my definition.

**Comment by jemc** [comment]
@non-Jedi - the receiver is the object that "receives" the method (function or behaviour) call.  In other words, it is the object that will be known as `this` inside the method or behaviour call.  In method calls with an explicit receiver, the receiver is whatever is on the left side of the `.` or `~`. When there is no explicit receiver in the syntax, the current `this` is used as the implicit receiver of the method call. When using method chaining (the `.>` symbol), the receiver is "carried forward" to be the result of the call expression, so that it can be used again as the receiver of the next call.

This use of "receiver" is general terminology for object-oriented programming languages, so you don't have to worry about any hidden details specific to Pony.

Hopefully that info helps it make a little more sense.

**Comment by non-Jedi** [comment]
@jemc Thanks. Didn't realize "receiver" was a generic OOP term. Extent of my OOP experience previously was python, where nobody seems to use that terminology. Since it's a generic term, doesn't seem like it really needs to be defined in a pony-specific tutorial.

Sorry for the noise.

**Comment by jemc** [comment]
No worries. I wasn't suggesting it shouldn't be added to the tutorial, just trying to give you some background.

If you still want to do a PR, please feel free.
