### ISSUE TITLE
`iftype` isn't documented in the tutorial

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/pony-tutorial#213]
see https://github.com/ponylang/rfcs/blob/master/text/0026-subtype-checking.md for more information

**Comment by jemc** [comment]
Last I knew, it was still considered experimental - @Praetonus do you think it should stay undocumented for now, or should it be mentioned in the tutorial?

**Comment by SeanTAllen** [comment]
I wasn't aware it was considered experimental. I missed that.

**Comment by Praetonus** [comment]
The feature isn't fully implemented as of now (`iftype`'d functions are still missing) and it's still clunky to use since function containing `iftype` blocks must be generic and generic type inference isn't implemented yet.

The first point isn't really a problem for documenting the existing part but the second point is worrying me. I'd prefer to hold on encouraging folks to use `iftype` until it's less cumbersome, and generic type inference is the blocker here.

**Comment by SeanTAllen** [comment]
I'll close for now.
