### ISSUE TITLE
Case functions section has no ">" link to proceed to next section

### ISSUE THREAD

**Issue by montsamu** [ponylang/pony-tutorial#268]
https://tutorial.ponylang.org/pattern-matching/case-functions.html

There is a "<" to go back, but no ">" to proceed to Chapter 7 (Code Sharing). This may because Chapter 7 does not really exist. Similarly, Chapter 8:

https://tutorial.ponylang.org/packages/

Has no "<" to go back.

**Comment by EpicEric** [comment]
Your assumption is correct. This is default behaviour for how GitBook detects the next/previous page. It checks the list in [SUMMARY.md](https://github.com/ponylang/pony-tutorial/blob/master/SUMMARY.md) for the current page, and sets the next/previous page link according to the item that follows/precedes respectively.

Currently, Chapter 7 has no link, since there is no page associated. Therefore, the ">"/"<" links won't appear, since there is nowhere to jump to.

I'm investigating if there is a way to skip over empty list items, either natively or through a plugin. Alternatively, it has also been suggested in #207 that Chapter 7 is removed altogether.

**Comment by jemc** [comment]
Case functions have bee removed. Is this issue ticket still valid?

**Comment by SeanTAllen** [comment]
Yes and no. The issue still exists. I think we should remove Chapter 7 that has no content. "Code sharing".
