### ISSUE TITLE
Partial application of functions ?

### ISSUE THREAD

**Issue by rodrigob** [ponylang/pony-tutorial#293]
The partial applications section describes the partial application of methods (inside objects); but does not mention partial application of pure functions.

https://github.com/ponylang/pony-tutorial/blob/9f69b9c8fe62b7349b721ac1a699f218b4850fad/expressions/partial-application.md#partial-application

It should at least mention if it is possible or not.

Would
```
fun add(a: U32, b:U32):U32 => a + b
let add3 = add~apply(where a=3)
add3(5)
```
work ?

**Comment by SeanTAllen** [comment]
It should be a minimally compile-able example. that code wouldn't compile.

**Comment by rodrigob** [comment]
but the point stand, does the language allow it ? Current tutorial seems to imply it is not an available feature.

**Comment by jemc** [comment]
Everything callable in pony is a method on an object (other than "bare functions", which are a construct for interacting via FFI with C code that expects function pointers). Note that it doesn't have to be an *allocated* object though - a method on a primitive is the Pony way of modeling a pure function, because primitives are a stateless, non-allocated kind of object that is mostly there to make the type system work in a uniform way.

Your example should probably be using `this~add` instead of `add~apply`.

**Comment by rodrigob** [comment]
I see, I had not grasped that there could not be global-level functions.
I guess I need to look into more real world pony code.

**Comment by jemc** [comment]
> Is there not sugar to partially apply a method of a type while delaying the application of the receiver (i.e. the object on which the method will be applied)?

No, there is no sugar for this at this time.

**Comment by SeanTAllen** [comment]
I believe this can be closed. If I was mistaken, please reopen with a clarification of what should be done to resolve this.
