### ISSUE TITLE
Matching just type?

### ISSUE THREAD

**Issue by jkleiser** [ponylang/pony-tutorial#30]
I find no info or example here http://tutorial.ponylang.org/pattern-matching/match/#matching-on-type-and-value about matching just on type. Is it possible? There are two examples starting like this:
```
fun f(x: (U32 | String | None)): String =>
```
I would like to see a case like this:
```
| String => "I got a String!"
```

**Comment by andymcn** [comment]
To match any value of a given type you need to use a capture as described in the "Captures" subsection of "Matching on type and value". The example given is:
```
| let s: String => s
```

You don't have to use the capture variable if you don't want to, this is fine:
```
| let s: String => "I got a String!"
```

Your example of:
```
| String => "I got a String!"
```
would create an empty String and match against that.

**Comment by jkleiser** [comment]
Thanks!

**Comment by jkleiser** [comment]
Have you considered this syntax?
```
| _: String => "I got a String!"
```

**Comment by andymcn** [comment]
That feels like an extra complication for no real gain. Is there a problem with the existing syntax?

**Comment by jkleiser** [comment]
The existing syntax is probably fine. I was just looking for a quick way to get around this error in my code:
this capture could violate capabilities, variable xyz may make more guarantees than the match operand
;-)

**Comment by andymcn** [comment]
If you don't need to use the capture, then making it tag should fix that
error for you:
`| let x: Type tag => ...`

**Comment by jkleiser** [comment]
I'm not quite there yet, but I'm working on it. Thanks. ;-)

**Comment by jkleiser** [comment]
Why am I getting "this capture could violate capabilities, variable t may make more guarantees than the match operand" on the line with "let t: MagicCarpet tag" in this code:
```
trait Vehicle
  fun size(): String

primitive MagicCarpet is Vehicle
  fun size(): String => "flexible"

class Truck is Vehicle
  var trailer: (Vehicle | None) = None
  fun size(): String => "Truck size"
  
  fun trailerInfo(): String =>
    match trailer
    | let t: None => "No trailer"
    | let t: MagicCarpet tag => "Strange trailer"
    else
      "Some trailer"
    end
```
And what can I do to solve it?

**Comment by andymcn** [comment]
The error you were seeing was due to a bug in the type checking code for matches. I've pushed a fix which should allow your code to work.

**Comment by jkleiser** [comment]
Thanks a lot! That was very good news. ;-)

**Comment by rurban** [comment]
In my little language (_cperl_, actually a big one) I added a `typeof` operator, which returns the compile-time type. And btw since it's a dynamic language also another `ref` operator, which returns the run-time type. Pony is easier here.
The question is to return it as some kind of type symbol (I choose `:type-expr`), or as string.

Those capture variables are not really useful.
    | let s: String => s
as the value is already in the match expression.

For this case:

    match x
    | let i: Int => "Int"
    | let f: F32|F64 => "float"
    | let s: String => "String"

I would prefer:
    | typeof x eq :String => "String"

which simplifies to
    | :String => "String"

So prefixing with `:` denotes a type expression, which might be needed to be parenthesized for complicated types.

The compiler can be even enhanced to look at the case expression and if the variable is not a literal and is unknown, but it's a valid type expression, use it as type expression. So you can omit the `:`, but of course adding a `:` looks much better for the casual reader, and helps the compiler.

**Comment by andymcn** [comment]
We're very much against having a general `typeof` operator. We feel it leads to people doing type things at runtime that really should be done at compile time, which is really the point of Pony. Also Pony types can be very complex, due to having unions, intersections, tuples, very general generics and capabilities and the interactions between those things. Representing them remotely efficiently at runtime is a tricky proposition.

We are however interested in improving the pattern match syntax, if that can be done sensibly.

A couple of points about how pattern matching currently works that I suspect you don't realise.

Firstly the capture variables are not merely useful, but actually essential. This is because although the value is available in the match expression it's the wrong type. Pony has strict typing, so you can't just cast things like you can in C. If you have something which is say `(U32 | None)` you can't use the integer value from it because you happen to know that's what is currently in it. You have to prove to the compiler that you actually have a U32 and that's what the capture variables are for.

Example:
```pony
fun f(x: (U32 | None)) =>
  let y: U32 = x + 3  // Error, None + 3 not defined
  
  match x
  | let x': U32 => let z = x' + 3 // OK
  end
```

In this example `x'` always has the same value as `x` within the matching case, but they have different types. `x'` is a `U32`, so you can use it. `x` is still a `(U32 | None)` which you can't really do anything with.

Secondly an expression (including a match pattern) consisting of just a type already has a meaning, due to Pony's default constructor sugar. When you have just a type on its own Pony adds a call to `create()` for you. So in expressions `String` is expanded to `String.create()`, which creates an empty string. This means that the following 3 match patterns are all actually identical:
```pony
match x
| String => ...
| String.create() => ...
| "" => ...
end
```

Clearly this means we can't use just the type in a pattern to match on the type.

Furthermore we can't allow complex types like unions in patterns without something to tell us it's a type, again because it's ambiguous.

All of this is why we currently require the capture variable.

So, could we improve the pattern syntax?

For simple cases we could use `:String` as you suggest. However, this goes a little wrong when handling tuples.

One of the great things about the Pony match is that you can simultaneously match some tuple elements against type and others against value. Example:
```pony
fun f(x: (U32, (String | F64), Bool)) =>
  match x
  | (3, let s: String, true) => ... // s not used
  | (4, let f: F64, _) => ... // f not used
  end
```

This means we'd have to accept the new `:String` syntax not just at the top level in the pattern, but also within tuples. Examples:
```pony
fun f(x: (U32, (String | None), Bool)) =>
  match x
  | (3, :String, true) => ...
  | (4, :F64, _) => ...
  end
```

It is possible to do this without causing clashes with any existing syntax. However it's only possible to allow it in those exact places, not just anywhere in expressions. This means that error messages related to trying to do that in the wrong place will be quite cryptic, which is something we try to avoid.

Finding some other syntax is an option. An obvious choice is the `typeof` you used. However, given that that is the same length as using a dummy capture it doesn't gain anything, so I'm not convinced it's worth adding.
```pony
match x
| let s: String => ...
| typeof String => ...
end
```

**Comment by SeanTAllen** [comment]
This is now in the documentation. Closing this issue. 

Any discussion of changing functionality of Pony should be moved to the pony dev mailing list at 

https://groups.io/g/pony+dev
