### ISSUE TITLE
Add Lifecycle Conversion Tutorial

### ISSUE THREAD

**Issue by allphfa** [ponylang/pony-tutorial#329]
How to convert between ref box trn iso val and ' and ^

Such as these conversions
```pony
use "debug"
actor Main

  be test(arg:String iso) =>
    Debug(arg)
    
  new create(env: Env) =>
    var aa = "123"
    test(aa.clone())
```

```pony
use "debug"
actor Main

  new create(env: Env) =>
    var aa = "123"
    val bb:String ref = aa
    
    Debug(bb)

```

**Comment by EpicEric** [comment]
For the first example, you cannot read from an `iso` reference without consuming it, as it would be unsafe. The [Consume and Destructive Read](https://tutorial.ponylang.io/capabilities/consume-and-destructive-read.html) section covers this topic. You would use `Debug(consume arg)` instead of `Debug(arg)` in line 5, as the compiler has no other way of knowing if `arg` will be read/written to later.

```pony
use "debug"

actor Main
  be test(arg: String iso) =>
    Debug(consume arg)

  new create(env: Env) =>
    var aa = "123" // Equivalent to `var aa: String val = "123"`
    test(aa.clone())
```

In the second example, `aa` implicitly has type `String val`. Thus, it cannot be converted to a `String ref` as it would violate capabilities (`ref` can be written to locally, while `val` is globally immutable -- more info in [Capability Subtyping](https://tutorial.ponylang.io/capabilities/capability-subtyping.html)). The only way to get a `String ref` would be creating a new object with the appropriate capability. Then we can use the `fun ref append()` method of the `String` class to copy data:

```pony
use "debug"

actor Main
  new create(env: Env) =>
    var aa = "123" // Equivalent to `var aa: String val = "123"`
    var bb: String ref = String // Equivalent to `var bb: String ref = String.create()`
    bb.append(aa)
    Debug(bb)
```

**Comment by allphfa** [comment]
Thank you, I thought it was the rust permission conversion, the original is similar to java string and stringbuffer type difference
