### ISSUE TITLE
Clarify a couple intro points

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/pony-tutorial#348]
In the intro to the tutorial, we mention that Pony is deadlock-free.

After watching https://www.twitch.tv/videos/378865137, I think its reasonable to assume that many people will interpret that was "livelock" free as well. A short clarification of that would make sense.

From the video, I think it also behooves us to expand a bit on "data race free" as it relates to concurrent access to memory as compared to "you wrote your algo wrong".

**Comment by rhagenson** [comment]
@SeanTAllen The video you linked in this issue is no longer available. Do you recall the video, and are you able to find an alternative link?

I see this issue as needing someone outside Pony as it a kind of "mismatched expectations" issue. After reading the [Introduction](https://tutorial.ponylang.io/) content, what does a new reader later realize was misleading?

Short list of points of clarification:
+ Deadlock-free is not livelock-free
+ Better explain data race free as seen in Pony

I also would like to get outside perspective on how we can make this first page a better bottom-line for Pony. For example, I think the "Guiding Principles" can be almost entirely removed, but I am too far removed from knowing if it contains useful information for new readers. (My thought on this is the "Guiding Principles" is too explicit a list for someone first arriving to Pony and is better expressed throughout the Tutorial as motivation for design elements.)

**Comment by SeanTAllen** [comment]
It was someone learning pony and recording it. Beyond that, I don't remember
