### ISSUE TITLE
Actors and sequentiality

### ISSUE THREAD

**Issue by ankush981** [ponylang/pony-tutorial#389]
So, the tutorial says:

> Actors themselves, however, are sequential. That is, each actor will only execute one behaviour at a time. This means all the code in an actor can be written without caring about concurrency: no need for locks or semaphores or anything like that.

My knowledge isn't extensive, but isn't one thing at a time exactly what concurrency is? Maybe the tutorial wanted to say "parallelism" instead of "concurrency"?

In any case, I find the interplay of "asynchronous" and "sequential" in the Sequential section really confusing. For instance:

```
actor Main
  new create(env: Env) =>
    call_me_later(env)
    env.out.print("This is printed first")

  be call_me_later(env: Env) =>
    env.out.print("This is printed last")
```

> In the example below, the Main actor calls a behaviour call_me_later which, as we know, is asynchronous, so we won’t wait for it to run before continuing. 

Fair enough. This is how asynchronous stuff is supposed to work anyway.

> Then, we run the method env.out.print, which is also asynchronous, and will print the provided text to the terminal.

Here I got stumped. The earlier sentence seems to be implying that we don't wait for asynchronous stuff, while the second one says the asynchronous method gets executed immediately!? Is it because it's the last statement inside the constructor?

Here's a modified example I tried myself:

```
actor Main
    new create(env: Env) =>
        call_me_later(env)
        call_me_later2(env)        
        env.out.print("This is printed first")

    be call_me_later(env: Env) =>
        env.out.print("call_me_later")
    
    be call_me_later2(env:Env) =>
        call_me_later3(env) 
        env.out.print("call_me_later2")
    
    be call_me_later3(env: Env) =>
        env.out.print("call_me_later3")
```

The output is:
```
This is printed first
call_me_later
call_me_later2
call_me_later3
```
From this, it seems to me that the relation between "asynchronous" and "sequential" isn't clearly explained in the tutorial. Why not simply say that because behaviors are asynchronous, calls to other behaviours get "queued up" and each behavior finishes its tasks before the next one can be executed. 

After writing this much, I'm beginning to get even more confused, honestly. It almost looks like the order of execution among chained behaviors is guaranteed, which shouldn't be the case. :sob: 

But hopefully, my ramblings provided some clarity on what the tutorial isn't explaining properly?

**Comment by jemc** [comment]
> My knowledge isn't extensive, but isn't one thing at a time exactly what concurrency is? Maybe the tutorial wanted to say "parallelism" instead of "concurrency"?

Maybe these definitions will help clear things up:
- Sequential basically means having a sequence of operations where the order is determined.
- Concurrency is introducing non-determinism into that order of operations - the fewer sequential order guarantees you make the less is determined, and the more concurrent those operations are.
- Parallelism is the act of leveraging the lack of order guarantees to actually start executing unrelated operations in parallel, letting you gain things done *faster*/*more efficiently* by using parallel cores rather than just getting things done in an undetermined order.

> Here I got stumped. The earlier sentence seems to be implying that we don't wait for asynchronous stuff, while the second one says the asynchronous method gets executed immediately!?

That's not what we mean here when we say "the method env.out.print, which is also asynchronous, and will print the provided text to the terminal" - we mean that it will print the provided text asynchronously, not immediately. We're open to ideas about how to make that more clear.

> After writing this much, I'm beginning to get even more confused, honestly. It almost looks like the order of execution among chained behaviors is guaranteed, which shouldn't be the case

There's something critical that the tutorial is failing to explain here, which is a concept called "causal message ordering". It should definitely have a section here, but it looks like we only give it a very brief mention in [this section](https://tutorial.ponylang.io/appendices/garbage-collection.html). It really deserves its own section here, so thanks for pointing it out.

In essence causal message ordering is a stronger guarantee than many other actor systems provide. It boils down to this: Multiple messages dispatched directly from a specific actor "A" to a specific actor "B" will be in the same order on "B" that they were on "A" - we say that they have a "causal" relation that guarantees this.

We definitely need to add a description of causal message ordering to the tutorial.

**Comment by ankush981** [comment]
> That's not what we mean here when we say "the method env.out.print, which is also asynchronous, and will print the provided text to the terminal" - we mean that it will print the provided text asynchronously, not immediately. We're open to ideas about how to make that more clear.

In that case, I think the focus of this tutorial section isn't clear. If we're talking about message ordering, who cares whether they are synchronous or asynchronous, at least for someone who is not into the nitty-gritty of distributed systems and just wants to get up and running with the language?!

> It boils down to this: Multiple messages dispatched directly from a specific actor "A" to a specific actor "B" will be in the same order on "B" that they were on "A" - we say that they have a "causal" relation that guarantees this.

This part is really helpful and should go into the documentation! And as I said before, I'd consider removing the "asynchronous" description for `env.out.print` -- for a simple tutorial, it's enough to say that though behaviors are asynchronous, the order of messages from Actor A to Actor B is guaranteed.

I now have a final point of confusion: what is the relation between causality and guaranteed ordering?   Sure, when Actor A sends messages to Actor B, it's "causing" them, but what internal mechanism ensures the order? Why is the order even necessary in a distributed world? :thinking:

**Comment by SeanTAllen** [comment]
> In that case, I think the focus of this tutorial section isn't clear. If we're talking about message ordering, who cares whether they are synchronous or asynchronous, at least for someone who is not into the nitty-gritty of distributed systems and just wants to get up and running with the language?!

What from Joe's response makes you think that we are talking about message ordering. It's unclear to me why you think its about message ordering based on what Joe said. Perhaps I am misunderstanding.

Btw, message ordering is important to sequentiality to that is why it would be discussed along with async/sync. The concepts are all tied together.

**Comment by SeanTAllen** [comment]
> Why is the order even necessary in a distributed world? 🤔

Why do you think that being able to make ordering guarantees isn't important?
If I have an open TCP connection and I send some data to be written and then send a message to close the socket. Do you think that the data should be written? Do you think I should be able to expect it has been written?

If you do, then you believe ordering is important.

**Comment by SeanTAllen** [comment]
> Sure, when Actor A sends messages to Actor B, it's "causing" them, but what internal mechanism 

You misunderstand the definition of "causal". It isn't meaning "causing". The casual relationship isn't between the Actors, it is between the messages that Actor A send to Actor B.

To repeat the TCP example:

1. write some data 
2. close

There's a casual relationship between those messages. I am sending "close" because I am done wanting to send some data. Perhaps this will help:

http://scattered-thoughts.net/blog/2012/08/16/causal-ordering/
