### ISSUE TITLE
Better docs format?

### ISSUE THREAD

**Issue by ankush981** [ponylang/pony-tutorial#390]
I earlier wanted to open this issue by saying we should move the docs from HTML pages to something like Readthedocs, but then realized that this was moved from GitBook to Hugo five months back. May I ask why?

The point is that the current theme being used isn't conducive for documentation. Navigation is hard, and on mobile, it's almost impossible to figure out where to go after reading the introduction. It seems I'm not alone on this, as I came across some not-so-old criticism on Reddit that the docs were very difficult to follow, and I have to agree.

Good news is, I'm happy to make the effort needed, but writing more CSS just doesn't seem to be the way. Why not move to something like Readthedocs? Are there better Hugo themes for documentation out there?

**Comment by SeanTAllen** [comment]
"Better" is very subjective.  Example, I detest read the docs and find it incredibly hard to work with.
Why hugo? We use hugo for everything else right now and I know it. Why is my knowing it important? Because I maintain it all and I want to use something I'm familiar with and not learn new and different tools. 

If you would like to propose fixes/changes within the current structure that is fine. It generally mirrors the basics of how Gitbook works. We moved off of Gitbook because it, the hosted option is abandoned and worked poorly and when we moved to hosting ourselves, the tool chain was regularly broken.

I disagree that the current theme "isn't conducive for documentation". That's a very general statement. I don't think its the basis for improvement. If you have specific ideas for improvement, I'm happy to discuss them and we can agree to solutions and improvements.
