### ISSUE TITLE
Document that partial application doesnt work with iso and trn parameters

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/pony-tutorial#439]
As seen via this example where it gets a compilation error:

https://playground.ponylang.io/?gist=056f09e2ab1be95390b103ad37833e3f

You can't use partial application with iso/trn parameters in the current implementation. Partial application is sugar over object literal creation.

@jemc states:

> I think it's an unfortunate limitation based on the fact that partial application is compiled to an object literal with captures, and the compiler doesn't know that it's a "use once" object literal
>
> In order to treat it as a "use once" object literal, it would need to be an iso object literal, but that has viewpoint adaptation implications that may mess up other arguments you're trying to send, so it can't be done that way in the general case

**Comment by rhagenson** [comment]
Closed by #445

**Comment by anacrolix** [comment]
Thanks, but could you provide a workaround for the sample code too? Now it's documented that it can't be done the way I originally expected, how should I do it?

**Comment by jemc** [comment]
@anacrolix - I copied the original playground code from the OP in this ticket (the example with `Herp` and `Derp`), and adapted it to use a class called `CreateHerp` rather than partial application syntax. The purpose of doing this is so that I could make the final application a `fun iso` that calls `consume this`, to represent to the compiler that this partial application object is one-time-use-only, thus upholding the required uniqueness guarantees that were missing in the version that uses partial application.

This may not be sufficient for every case, but it at least works for the case in the playground example. Here's the sample code: https://playground.ponylang.io/?gist=056f09e2ab1be95390b103ad37833e3f

```pony
class iso Derp

actor Herp
  new create(derp: Derp, env: Env) =>
    env.out.print("hooray!")

class iso CreateHerp
  let _derp: Derp
  new iso create(derp: Derp) => _derp = consume derp
  fun iso apply(env: Env): Herp => Herp((consume this)._derp, env)

actor Main
  new create(env: Env) =>
    let partially_applied_thing = CreateHerp(Derp)
```

**Comment by anacrolix** [comment]
Thanks!
