### ISSUE TITLE
Update misleading `as` documentation

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/pony-tutorial#485]
Reading the "As documentation"- https://tutorial.ponylang.io/pattern-matching/as.html#safely-converting-to-a-more-specific-type-casting I think it should be changed.

In particular it uses the words "casting" and "converting" neither of which are true for what "as" does.

I think it should be rewritten to talk about "as" as a shorthand for "match X type or error" at runtime. It never converts to another type, it never changes to another type.

There's some more nuance that needs to go into that related to how interfaces work and what people think it means in that example to "convert the interface" but I think this would be best explained via match not "casting".

I've seen a lot of people think that "as" changes the type of something which is not true, but reading the documentation in the tutorial, I can see why they think that.

After discussion in Zulip, it was decided that in general the format should be:

- every value has exactly one "true"/concrete type it is an instance of
- that concrete type can be subsumed inside of more general/abstract types that it is a subset/subtype of
- normal assignment/passing semantics let a value only move "down" into less specific / more general levels of abstraction (or stay at the same level it is)
- using as or match can let you move back "up" to more specific types by checking the type information at runtime

I personally think we should avoid using the terms "down" and "up" but at the moment, I don't have better terminology. If we do use "down" and "up" we should give examples that hopefully short-circuit the belief some people will have that subtyping in Pony is equivalent to inheritance in some other languages. I am worried that people will interpret "up" and "down" with "an inheritance mindset".

See https://ponylang.zulipchat.com/#narrow/stream/190368-tutorial/topic/As.20documentation for additional context.

**Comment by niclash** [comment]
Suggestion;
"Each value has one or more types, and each alias is of one or more types. `as` allows an aliased value to be viewed as one of the other types of the value. Examples;"
Something like that will avoid "up/down" and the inheritance mindset altogether, especially since Pony types are "more" than inherited type trees.

**Comment by niclash** [comment]
Before issuing a PR, I would like to get feedback on my first attempt; https://github.com/niclash/pony-tutorial/blob/main/docs/pattern-matching/as.md

I was contemplating using "expressing" or "exposing" the instance type, and settled with "expressing". 

The text doesn't fully follow the outline in the OP, mainly because (as noted) up/down is completely wrong nomenclature. I also think examples are easier than convoluted texts trying to express what becomes almost obvious in code, and perhaps even more short examples should be there.
