### ISSUE TITLE
Flesh out "getting started with pony"

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/pony-tutorial#72]
It's pretty barren:

http://tutorial.ponylang.org/getting-started/index.html

**Comment by rhagenson** [comment]
@SeanTAllen I think the intro has been "fleshed out" since this issue was created. I take other issue with the intro here -- use of contractions, inclusion of matters that do not get a person started, an immediate link to the most difficult Pony concept (refcaps) well before a reader has context to understand the content of the link.

Do we want to re-purpose this issue to "clean" the intro rather than flesh it out?
